export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAILD = "PRODUCT_DETAIL_FAILD";
export const PRODUCT_DETAIL_CLEAR = "PRODUCT_DETAIL_CLEAR";
export const PRODUCT_DETAIL_LONG = "PRODUCT_DETAIL_LONG";
export const PRODUCT_DETAIL_NO_DATA = "PRODUCT_DETAIL_NO_DATA";


export const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST";
export const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS";
export const PRODUCT_REVIEW_FAILD = "PRODUCT_REVIEW_FAILD";
export const PRODUCT_REVIEW_CLEAR = "PRODUCT_REVIEW_CLEAR";
export const PRODUCT_REVIEW_LONG = "PRODUCT_REVIEW_LONG";
export const PRODUCT_REVIEW_NO_DATA = "PRODUCT_REVIEW_NO_DATA";


export const ADD_PRODUCT_REVIEW_REQUEST = "ADD_PRODUCT_REVIEW_REQUEST";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAILD = "ADD_PRODUCT_REVIEW_FAILD";
export const ADD_PRODUCT_REVIEW_CLEAR = "ADD_PRODUCT_REVIEW_CLEAR";
export const ADD_PRODUCT_REVIEW_LONG = "ADD_PRODUCT_REVIEW_LONG";
export const ADD_PRODUCT_REVIEW_NO_DATA = "ADD_PRODUCT_REVIEW_NO_DATA";


export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILD = "ADD_TO_CART_FAILD";
export const ADD_TO_CART_CLEAR = "ADD_TO_CART_CLEAR";
export const ADD_TO_CART_LONG = "ADD_TO_CART_LONG";
export const ADD_TO_CART_NO_DATA = "ADD_TO_CART_NO_DATA";

export const SELECT_VARIENT_REQUEST = "SELECT_VARIENT_REQUEST";
export const SELECT_VARIENT_SUCCESS = "SELECT_VARIENT_SUCCESS";
export const SELECT_VARIENT_FAILD = "SELECT_VARIENT_FAILD";
export const SELECT_VARIENT_CLEAR = "SELECT_VARIENT_CLEAR";
export const SELECT_VARIENT_LONG = "SELECT_VARIENT_LONG";
export const SELECT_VARIENT_NO_DATA = "SELECT_VARIENT_NO_DATA";


export const NOTIFY_ME_REQUEST = "NOTIFY_ME_REQUEST";
export const NOTIFY_ME_SUCCESS = "NOTIFY_ME_SUCCESS";
export const NOTIFY_ME_FAILD = "NOTIFY_ME_FAILD";
export const NOTIFY_ME_CLEAR = "NOTIFY_ME_CLEAR";
export const NOTIFY_ME_LONG = "NOTIFY_ME_LONG";
export const NOTIFY_ME_NO_DATA = "NOTIFY_ME_NO_DATA";