export const WISH_LIST_REQUEST = "WISH_LIST_REQUEST";
export const WISH_LIST_SUCCESS = "WISH_LIST_SUCCESS";
export const WISH_LIST_FAILD = "WISH_LIST_FAILD";
export const WISH_LIST_CLEAR = "WISH_LIST_CLEAR";
export const WISH_LIST_NO_DATA = "WISH_LIST_NO_DATA";
export const WISH_LIST_LONG = "WISH_LIST_LONG";