export const MY_SETTING_REQUEST = "MY_SETTING_REQUEST";
export const MY_SETTING_SUCCESS = "MY_SETTING_SUCCESS";
export const MY_SETTING_FAILD = "MY_SETTING_FAILD";
export const MY_SETTING_CLEAR = "MY_SETTING_CLEAR";
export const MY_SETTING_LONG = "MY_SETTING_LONG";

export const MY_SETTING_UPDATE_REQUEST = "MY_SETTING_UPDATE_REQUEST";
export const MY_SETTING_UPDATE_SUCCESS = "MY_SETTING_UPDATE_SUCCESS";
export const MY_SETTING_UPDATE_FAILD = "MY_SETTING_UPDATE_FAILD";
export const MY_SETTING_UPDATE_CLEAR = "MY_SETTING_UPDATE_CLEAR";
export const MY_SETTING_UPDATE_LONG = "MY_SETTING_UPDATE_LONG";