export const MYADDRESSES_REQUEST = "MYADDRESSES_REQUEST";
export const MYADDRESSES_SUCCESS = "MYADDRESSES_SUCCESS";
export const MYADDRESSES_FAILD = "MYADDRESSES_FAILD";
export const MYADDRESSES_CLEAR = "MYADDRESSES_CLEAR";
export const MYADDRESSES_LONG = "MYADDRESSES_LONG";

export const MYADDRESSES_ADD_UPDATE_REQUEST = "MYADDRESSES_ADD_UPDATE_REQUEST";
export const MYADDRESSES_ADD_UPDATE_SUCCESS = "MYADDRESSES_ADD_UPDATE_SUCCESS";
export const MYADDRESSES_ADD_UPDATE_FAILD = "MYADDRESSES_ADD_UPDATE_FAILD";
export const MYADDRESSES_ADD_UPDATE_CLEAR = "MYADDRESSES_ADD_UPDATE_CLEAR";
export const MYADDRESSES_ADD_UPDATE_LONG = "MYADDRESSES_ADD_UPDATE_LONG";

export const MYADDRESSES_DELETE_REQUEST = "MYADDRESSES_DELETE_REQUEST";
export const MYADDRESSES_DELETE_SUCCESS = "MYADDRESSES_DELETE_SUCCESS";
export const MYADDRESSES_DELETE_FAILD = "MYADDRESSES_DELETE_FAILD";
export const MYADDRESSES_DELETE_CLEAR = "MYADDRESSES_DELETE_CLEAR";
export const MYADDRESSES_DELETE_LONG = "MYADDRESSES_DELETE_LONG";