export const MYCART_REQUEST = "MYCART_REQUEST";
export const MYCART_SUCCESS = "MYCART_SUCCESS";
export const MYCART_FAILD = "MYCART_FAILD";
export const MYCART_CLEAR = "MYCART_CLEAR";
export const MYCART_LONG = "MYCART_LONG";
export const MYCART_NO_DATA = "MYCART_NO_DATA";

export const ADD_REMOVE_CART_FROM_MINICART_REQUEST = "ADD_REMOVE_CART_FROM_MINICART_REQUEST";
export const ADD_REMOVE_CART_FROM_MINICART_SUCCESS = "ADD_REMOVE_CART_FROM_MINICART_SUCCESS";
export const ADD_REMOVE_CART_FROM_MINICART_FAILD = "ADD_REMOVE_CART_FROM_MINICART_FAILD";
export const ADD_REMOVE_CART_FROM_MINICART_CLEAR = "ADD_REMOVE_CART_FROM_MINICART_CLEAR";
export const ADD_REMOVE_CART_FROM_MINICART_LONG = "ADD_REMOVE_CART_FROM_MINICART_LONG";
export const ADD_REMOVE_CART_FROM_MINICART_NO_DATA = "ADD_REMOVE_CART_FROM_MINICART_NO_DATA";

export const MYCART_GLOBAL = "MYCART_GLOBAL";