export const INSPIRATION_DETAIL_REQUEST = "INSPIRATION_DETAIL_REQUEST";
export const INSPIRATION_DETAIL_SUCCESS = "INSPIRATION_DETAIL_SUCCESS";
export const INSPIRATION_DETAIL_FAILD = "INSPIRATION_DETAIL_FAILD";
export const INSPIRATION_DETAIL_CLEAR = "INSPIRATION_DETAIL_CLEAR";
export const INSPIRATION_DETAIL_LONG = "INSPIRATION_DETAIL_LONG";
export const INSPIRATION_DETAIL_NO_DATA = "INSPIRATION_DETAIL_NO_DATA";