export const RECIPE_DETAIL_REQUEST = "RECIPE_DETAIL_REQUEST";
export const RECIPE_DETAIL_SUCCESS = "RECIPE_DETAIL_SUCCESS";
export const RECIPE_DETAIL_FAILD = "RECIPE_DETAIL_FAILD";
export const RECIPE_DETAIL_CLEAR = "RECIPE_DETAIL_CLEAR";
export const RECIPE_DETAIL_LONG = "RECIPE_DETAIL_LONG";
export const RECIPE_DETAIL_NO_DATA = "RECIPE_DETAIL_NO_DATA";


export const RECIPE_DETAIL_SUBMIT_REVIEW_REQUEST = "RECIPE_DETAIL_SUBMIT_REVIEW_REQUEST";
export const RECIPE_DETAIL_SUBMIT_REVIEW_SUCCESS = "RECIPE_DETAIL_SUBMIT_REVIEW_SUCCESS";
export const RECIPE_DETAIL_SUBMIT_REVIEW_FAILD = "RECIPE_DETAIL_SUBMIT_REVIEW_FAILD";
export const RECIPE_DETAIL_SUBMIT_REVIEW_CLEAR = "RECIPE_DETAIL_SUBMIT_REVIEW_CLEAR";
export const RECIPE_DETAIL_SUBMIT_REVIEW_LONG = "RECIPE_DETAIL_SUBMIT_REVIEW_LONG";
export const RECIPE_DETAIL_SUBMIT_REVIEW_NO_DATA = "RECIPE_DETAIL_SUBMIT_REVIEW_NO_DATA";


export const RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_REQUEST = "RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_REQUEST";
export const RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_SUCCESS = "RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_SUCCESS";
export const RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_FAILD = "RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_FAILD";
export const RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_CLEAR = "RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_CLEAR";
export const RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_LONG = "RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_LONG";
export const RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_NO_DATA = "RECIPE_DETAIL_SUBMIT_REVIEW_REPLY_NO_DATA";