export const INSPIRATION_CATEGORY_REQUEST = "INSPIRATION_CATEGORY_REQUEST";
export const INSPIRATION_CATEGORY_SUCCESS = "INSPIRATION_CATEGORY_SUCCESS";
export const INSPIRATION_CATEGORY_FAILD = "INSPIRATION_CATEGORY_FAILD";
export const INSPIRATION_CATEGORY_CLEAR = "INSPIRATION_CATEGORY_CLEAR";
export const INSPIRATION_CATEGORY_NO_DATA = "INSPIRATION_CATEGORY_NO_DATA";
export const INSPIRATION_CATEGORY_LONG = "INSPIRATION_CATEGORY_LONG";