export const MYACCOUNT_REQUEST = "MYACCOUNT_REQUEST";
export const MYACCOUNT_SUCCESS = "MYACCOUNT_SUCCESS";
export const MYACCOUNT_FAILD = "MYACCOUNT_FAILD";
export const MYACCOUNT_CLEAR = "MYACCOUNT_CLEAR";
export const MYACCOUNT_LONG = "MYACCOUNT_LONG";