export const COUNTRY_REQUEST = "COUNTRY_REQUEST";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_FAILD = "COUNTRY_FAILD";
export const COUNTRY_CLEAR = "COUNTRY_CLEAR";
export const COUNTRY_LONG = "COUNTRY_LONG";