export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILD = "ORDER_LIST_FAILD";
export const ORDER_LIST_CLEAR = "ORDER_LIST_CLEAR";
export const ORDER_LIST_LONG = "ORDER_LIST_LONG";
export const ORDER_LIST_NO_DATA = "ORDER_LIST_NO_DATA";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAILD = "ORDER_DETAIL_FAILD";
export const ORDER_DETAIL_CLEAR = "ORDER_DETAIL_CLEAR";
export const ORDER_DETAIL_LONG = "ORDER_DETAIL_LONG";
export const ORDER_DETAIL_NO_DATA = "ORDER_DETAIL_NO_DATA";