export const MEGA_MENU_REQUEST = "MEGA_MENU_REQUEST";
export const MEGA_MENU_SUCCESS = "MEGA_MENU_SUCCESS";
export const MEGA_MENU_FAILD = "MEGA_MENU_FAILD";
export const MEGA_MENU_CLEAR = "MEGA_MENU_CLEAR";
export const MEGA_MENU_LONG = "MEGA_MENU_LONG";
export const MEGA_MENU_NO_DATA = "MEGA_MENU_NO_DATA";