export const MYPROFILE_REQUEST = "MYPROFILE_REQUEST";
export const MYPROFILE_SUCCESS = "MYPROFILE_SUCCESS";
export const MYPROFILE_FAILD = "MYPROFILE_FAILD";
export const MYPROFILE_CLEAR = "MYPROFILE_CLEAR";
export const MYPROFILE_LONG = "MYPROFILE_LONG";


export const MYPROFILE_UPDATE_REQUEST = "MYPROFILE_UPDATE_REQUEST";
export const MYPROFILE_UPDATE_SUCCESS = "MYPROFILE_UPDATE_SUCCESS";
export const MYPROFILE_UPDATE_FAILD = "MYPROFILE_UPDATE_FAILD";
export const MYPROFILE_UPDATE_CLEAR = "MYPROFILE_UPDATE_CLEAR";
export const MYPROFILE_UPDATE_LONG = "MYPROFILE_UPDATE_LONG";