export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILD = "CONTACT_US_FAILD";
export const CONTACT_US_CLEAR = "CONTACT_US_CLEAR";
export const CONTACT_US_LONG = "CONTACT_US_LONG";