export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILD = "PRODUCT_LIST_FAILD";
export const PRODUCT_LIST_CLEAR = "PRODUCT_LIST_CLEAR";
export const PRODUCT_LIST_LONG = "PRODUCT_LIST_LONG";
export const PRODUCT_LIST_NO_DATA = "PRODUCT_LIST_NO_DATA";


export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILD = "CATEGORY_LIST_FAILD";
export const CATEGORY_LIST_CLEAR = "CATEGORY_LIST_CLEAR";
export const CATEGORY_LIST_LONG = "CATEGORY_LIST_LONG";
export const CATEGORY_LIST_NO_DATA = "CATEGORY_LIST_NO_DATA";