export const PROMO_CODE_REQUEST = "PROMO_CODE_REQUEST";
export const PROMO_CODE_SUCCESS = "PROMO_CODE_SUCCESS";
export const PROMO_CODE_FAILD = "PROMO_CODE_FAILD";
export const PROMO_CODE_CLEAR = "PROMO_CODE_CLEAR";
export const PROMO_CODE_LONG = "PROMO_CODE_LONG";