export const INSPIRATION_REQUEST = "INSPIRATION_REQUEST";
export const INSPIRATION_SUCCESS = "INSPIRATION_SUCCESS";
export const INSPIRATION_FAILD = "INSPIRATION_FAILD";
export const INSPIRATION_CLEAR = "INSPIRATION_CLEAR";
export const INSPIRATION_LONG = "INSPIRATION_LONG";