export const RECIPE_CATEGORY_REQUEST = "RECIPE_CATEGORY_REQUEST";
export const RECIPE_CATEGORY_SUCCESS = "RECIPE_CATEGORY_SUCCESS";
export const RECIPE_CATEGORY_FAILD = "RECIPE_CATEGORY_FAILD";
export const RECIPE_CATEGORY_CLEAR = "RECIPE_CATEGORY_CLEAR";
export const RECIPE_CATEGORY_NO_DATA = "RECIPE_CATEGORY_NO_DATA";
export const RECIPE_CATEGORY_LONG = "RECIPE_CATEGORY_LONG";