export const DELETE_ACCOUNT_REQUEST = "DELETE_ACCOUNT_REQUEST";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILD = "DELETE_ACCOUNT_FAILD";
export const DELETE_ACCOUNT_CLEAR = "DELETE_ACCOUNT_CLEAR";
export const DELETE_ACCOUNT_LONG = "DELETE_ACCOUNT_LONG";


export const DELETE_ACCOUNT_ACTION_REQUEST = "DELETE_ACCOUNT_ACTION_REQUEST";
export const DELETE_ACCOUNT_ACTION_SUCCESS = "DELETE_ACCOUNT_ACTION_SUCCESS";
export const DELETE_ACCOUNT_ACTION_FAILD = "DELETE_ACCOUNT_ACTION_FAILD";
export const DELETE_ACCOUNT_ACTION_CLEAR = "DELETE_ACCOUNT_ACTION_CLEAR";
export const DELETE_ACCOUNT_ACTION_LONG = "DELETE_ACCOUNT_ACTION_LONG";