export const STATE_REQUEST = "STATE_REQUEST";
export const STATE_SUCCESS = "STATE_SUCCESS";
export const STATE_FAILD = "STATE_FAILD";
export const STATE_CLEAR = "STATE_CLEAR";
export const STATE_LONG = "STATE_LONG";

export const STATE_FOR_ADD_ADDRESS_POPUP_REQUEST = "STATE_FOR_ADD_ADDRESS_POPUP_REQUEST";
export const STATE_FOR_ADD_ADDRESS_POPUP_SUCCESS = "STATE_FOR_ADD_ADDRESS_POPUP_SUCCESS";
export const STATE_FOR_ADD_ADDRESS_POPUP_FAILD = "STATE_FOR_ADD_ADDRESS_POPUP_FAILD";
export const STATE_FOR_ADD_ADDRESS_POPUP_CLEAR = "STATE_FOR_ADD_ADDRESS_POPUP_CLEAR";
export const STATE_FOR_ADD_ADDRESS_POPUP_LONG = "STATE_FOR_ADD_ADDRESS_POPUP_LONG";